# -*- coding: utf-8 -*-
"""FloodPredictiveModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyTUJS9S7jaZ1LKCV2LHQjnxwphXWDqE

## Flood Prediction Model - Random Forest Classification with Continual Learning Pipeline

###Features:
  - Initial training on historical + synthetic data
  - Receives new sensor data from two csv files generated from the dashbaord
  - Rolling window: every 1000 new rows, delete the first 1000 old rows
  - Retrain automatically when rolling threshold is hit
  - Model archive: 5 models maximum, worst model is deleted when cap is exceeded
  - best_model.pkl: always points to the best performing model
  - Live prediction: returns flood occurence classification with confidence score
  - Notifies dashboard when bes model has been updated in the folder

###How to connect to dashboard:
  - Dashbaord calls two API endpoints (defined in app.py)
  - POST /ingest = sending sensor data here to save and trigger retrain
  - POST /predict = sending live sensor values, gets flood prediction back
"""

import os
import pickle
import shutil
import json
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from datetime import datetime
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    confusion_matrix, ConfusionMatrixDisplay,
    classification_report, accuracy_score,
    roc_curve, auc, f1_score
)

FEATURES      = ["Rainfall_mm", "WaterLevel_m", "SoilMoisture_pct", "Elevation_m"]
TARGET        = "FloodOccurrence"
MODEL_COLUMNS = FEATURES + [TARGET]
FLOOD_TYPE_COL = "FloodType"
SYNTHETIC_COL = "synthetic"
UNLABELLED_FLOOD_TYPE = False
TRAINING_METADATA_DEFAULTS = {
    "RuleFloodOccurrence": 0,
    "RuleFRI": 0.0,
    "RuleRiskText": "None",
    "RuleFloodType": "None",
    "AIFloodOccurrence": 0,
    "AIConfidence": 0.0,
    "FinalFloodOccurrence": 0,
}

BASE_DIR      = Path(__file__).resolve().parent
DATA_DIR      = BASE_DIR / "data"
RAW_DIR       = DATA_DIR / "raw"
ROLLING_DIR   = DATA_DIR / "rolling"
ANCHOR_DIR    = DATA_DIR / "anchor"

for folder in [RAW_DIR, ROLLING_DIR, ANCHOR_DIR]:
    folder.mkdir(parents=True, exist_ok=True)

# Region CSV files
REGION_A_CSV  = ROLLING_DIR / "region_a_rolling.csv"
REGION_B_CSV  = ROLLING_DIR / "region_b_rolling.csv"

# Retraining settings
ROLLING_KEEP_SIZE = 7187  # target rows to keep in each region rolling CSV
ROLLING_SIZE      = 10   # new rows before retrain triggers + oldest rows dropped
MAX_MODELS    = 5       # max models kept in archive at any time

# File paths
MODEL_DIR     = "models"           # folder for all saved model versions
BEST_MODEL    = "best_model.pkl"   # always the best model — dashboard loads this
HOLDOUT_FILE  = RAW_DIR / "flood_test_real.csv" # fixed test set, never trained on
ANCHOR_FILE   = ANCHOR_DIR / "anchor_set.csv"   # top 50 extreme flood events, never deleted

# Random Forest settings
RF_PARAMS = dict(
    n_estimators = 200,
    max_depth    = 10,
    random_state = 42,
    n_jobs       = -1,
)

os.makedirs(MODEL_DIR, exist_ok=True)

# Per-region model layout (atomic deploy + archive rotation)
MODEL_BASE   = Path(MODEL_DIR)
CURRENT_DIR  = MODEL_BASE / "current"
ARCHIVE_DIR  = MODEL_BASE / "archive"
BEST_MODEL_PATH = MODEL_BASE / BEST_MODEL

for d in [CURRENT_DIR, ARCHIVE_DIR]:
    d.mkdir(parents=True, exist_ok=True)

# Chart Styling
ACCENT   = "#4fc3f7"
BG_MAIN  = "#0f1117"
BG_PANEL = "#1a1d27"
TEXT_COL = "#e0e0e0"
GRID_COL = "#2e3148"

def style_ax(ax, title):
    ax.set_facecolor(BG_PANEL)
    ax.tick_params(colors=TEXT_COL, labelsize=9)
    ax.xaxis.label.set_color(TEXT_COL)
    ax.yaxis.label.set_color(TEXT_COL)
    ax.title.set_color(TEXT_COL)
    ax.set_title(title, fontsize=12, fontweight="bold", pad=10)
    for spine in ax.spines.values():
        spine.set_edgecolor(GRID_COL)

# Model archive utilities
# - keeps up to maximum 5 models
# - if there are more than 5 models, all are scored and the worst performing model gets deleted
# - best performing model gets copied to best_model.pkl so the dahabord always knows which model to use

def _score_model_file(pkl_path, X_hold, y_hold):
    """
    Load a saved model file and return its F1 score on the holdout set.
    Used to compare models against each other.
    """
    with open(pkl_path, "rb") as f:
        m = pickle.load(f)
    y_pred = m.predict(X_hold)
    return f1_score(y_hold, y_pred, zero_division=0)


def _save_model_metadata(model_path, metrics, train_count, flood_count):
    """Save JSON metadata alongside a model file.
    
    Metadata includes: timestamp, F1, accuracy, AUC, train/flood counts.
    Useful for reproducibility and audit trails.
    """
    metadata_path = Path(model_path).with_suffix('.json')
    metadata = {
        "model_file": Path(model_path).name,
        "timestamp": datetime.now().isoformat(),
        "metrics": {
            "f1": float(metrics.get("f1", 0)),
            "accuracy": float(metrics.get("acc", 0)),
            "auc": float(metrics.get("auc", 0)),
        },
        "training_data": {
            "total_rows": int(train_count),
            "flood_events": int(flood_count),
            "flood_ratio": float(flood_count / train_count) if train_count > 0 else 0,
        }
    }
    with open(metadata_path, "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"  [metadata] Saved → {metadata_path}")


def get_archive():
    """
    Return a sorted list of all saved model file paths in models/ folder.
    Excludes best_model.pkl itself.
    """
    files = sorted([
        f for f in os.listdir(ARCHIVE_DIR)
        if f.endswith(".pkl")
    ])
    return [str(ARCHIVE_DIR / f) for f in files]

def _update_best_model(X_hold, y_hold):
    """
    Score all archived models, find the best one, and copy it to
    best_model.pkl. The dashboard always loads best_model.pkl —
    this ensures it always gets the best performing version.
    """
    archive = get_archive()
    if not archive:
        return None

    scores    = {p: _score_model_file(p, X_hold, y_hold) for p in archive}
    best_path = max(scores, key=scores.get)
    best_f1   = scores[best_path]

    shutil.copy(best_path, BEST_MODEL_PATH)
    print(f"  [best] {BEST_MODEL_PATH.name} updated → "
          f"{os.path.basename(best_path)} (F1={best_f1:.4f})")
    return best_path

def _list_region_archive(region: str):
    """Return list of archive files for a given region, sorted."""
    files = sorted([
        f for f in os.listdir(ARCHIVE_DIR)
        if f.endswith(".pkl") and f.startswith(f"model_{region}_")
    ])
    return [str(ARCHIVE_DIR / f) for f in files]


def _save_region_model_legacy(model, region: str, version_tag: str, X_hold, y_hold):
    """
    Atomically save a model for a specific region.
    - archive: models/archive/model_<region>_<version>.pkl
    - current: models/current/<region>.pkl (atomic replace)
    - perform archive rotation per-region using F1 on holdout
    - save metadata JSON for reproducibility
    """
    # Archive save (atomic)
    archive_name = f"model_{region}_{version_tag}.pkl"
    archive_path = ARCHIVE_DIR / archive_name
    tmp_archive  = ARCHIVE_DIR / (archive_name + ".tmp")
    with open(tmp_archive, "wb") as f:
        pickle.dump(model, f)
    os.replace(tmp_archive, archive_path)
    print(f"  [archive:{region}] Saved → {archive_path}")

    # Score and save metadata
    y_pred = model.predict(X_hold)
    metrics = evaluate(model, X_hold, y_hold, label="")
    _save_model_metadata(str(archive_path), metrics, len(X_hold), int(y_hold.sum()))

    # Deploy current model atomically
    current_name = f"{region}.pkl"
    current_path = CURRENT_DIR / current_name
    tmp_current  = CURRENT_DIR / (current_name + ".tmp")
    with open(tmp_current, "wb") as f:
        pickle.dump(model, f)
    os.replace(tmp_current, current_path)
    print(f"  [current:{region}] Deployed → {current_path}")

    # Archive rotation per-region
    files = _list_region_archive(region)
    if len(files) > MAX_MODELS:
        print(f"  [archive:{region}] Cap of {MAX_MODELS} exceeded. Scoring models...")
        scores = {p: _score_model_file(p, X_hold, y_hold) for p in files}
        for p, s in scores.items():
            print(f"    {os.path.basename(p)}: F1={s:.4f}")
        worst = min(scores, key=scores.get)
        os.remove(worst)
        # Also remove metadata if it exists
        metadata_path = Path(worst).with_suffix('.json')
        if metadata_path.exists():
            os.remove(metadata_path)
        print(f"  [archive:{region}] Removed worst → {os.path.basename(worst)} "
              f"(F1={scores[worst]:.4f})")

    return str(archive_path)

def save_region_model(model, region: str, version_tag: str, X_hold, y_hold):
    """
    Save a candidate model for one region and deploy that region's best archive.
    This definition intentionally supersedes the earlier compatibility version.
    """
    region = region.lower()
    archive_name = f"model_{region}_{version_tag}.pkl"
    archive_path = ARCHIVE_DIR / archive_name
    tmp_archive  = ARCHIVE_DIR / (archive_name + ".tmp")
    with open(tmp_archive, "wb") as f:
        pickle.dump(model, f)
    os.replace(tmp_archive, archive_path)
    print(f"  [archive:{region}] Saved -> {archive_path}")

    metrics = evaluate(model, X_hold, y_hold, label="")
    _save_model_metadata(str(archive_path), metrics, len(X_hold), int(y_hold.sum()))

    files = _list_region_archive(region)
    if len(files) > MAX_MODELS:
        print(f"  [archive:{region}] Cap of {MAX_MODELS} exceeded. Scoring models...")
        scores = {p: _score_model_file(p, X_hold, y_hold) for p in files}
        for p, s in scores.items():
            print(f"    {os.path.basename(p)}: F1={s:.4f}")
        worst = min(scores, key=scores.get)
        os.remove(worst)
        metadata_path = Path(worst).with_suffix(".json")
        if metadata_path.exists():
            os.remove(metadata_path)
        print(f"  [archive:{region}] Removed worst -> {os.path.basename(worst)} "
              f"(F1={scores[worst]:.4f})")

    files = _list_region_archive(region)
    scores = {p: _score_model_file(p, X_hold, y_hold) for p in files}
    best_path = max(scores, key=scores.get)
    best_f1 = scores[best_path]

    current_path = CURRENT_DIR / f"{region}.pkl"
    tmp_current  = CURRENT_DIR / (f"{region}.pkl.tmp")
    shutil.copy(best_path, tmp_current)
    os.replace(tmp_current, current_path)
    print(f"  [current:{region}] Deployed best -> {current_path} "
          f"from {os.path.basename(best_path)} (F1={best_f1:.4f})")

    return str(best_path)


def save_to_archive(model, version_tag, X_hold, y_hold):
    """
    Save a new model to the archive with a timestamp filename.
    If archive now exceeds MAX_MODELS, score all models and delete
    the worst performer. Then update best_model.pkl.
    """
    # Backwards-compatible placeholder — use save_to_archive_global() for global archive
    raise TypeError("save_to_archive() must not be called directly. Use save_to_archive_global() or save_region_model().")


def save_to_archive_global(model, version_tag, X_hold, y_hold):
    """
    Original (global) archive behaviour preserved for backwards compatibility.
    Saves to models/archive/model_<version_tag>.pkl, enforces MAX_MODELS
    across all archived models and then updates the global best model.
    Also saves metadata JSON for reproducibility.
    """
    path = str(ARCHIVE_DIR / f"model_{version_tag}.pkl")
    with open(path, "wb") as f:
        pickle.dump(model, f)
    print(f"  [archive] Saved → {path}")

    # Score and save metadata
    y_pred = model.predict(X_hold)
    metrics = evaluate(model, X_hold, y_hold, label="")
    _save_model_metadata(path, metrics, len(X_hold), int(y_hold.sum()))

    archive = get_archive()
    if len(archive) > MAX_MODELS:
        print(f"  [archive] Cap of {MAX_MODELS} exceeded. Scoring all models...")
        scores = {p: _score_model_file(p, X_hold, y_hold) for p in archive}
        for p, s in scores.items():
            print(f"    {os.path.basename(p)}: F1={s:.4f}")
        worst = min(scores, key=scores.get)
        os.remove(worst)
        # Also remove metadata if it exists
        metadata_path = Path(worst).with_suffix('.json')
        if metadata_path.exists():
            os.remove(metadata_path)
        print(f"  [archive] Removed worst → {os.path.basename(worst)} "
              f"(F1={scores[worst]:.4f})")

    _update_best_model(X_hold, y_hold)

def load_best_model():
    """
    Load best_model.pkl — the best performing model in the archive.
    This is what predict_live() uses for every prediction.
    The dashboard is told to reload this file when best_model_updated=True
    is returned from the /ingest API endpoint.
    """
    if not BEST_MODEL_PATH.exists():
        raise RuntimeError(
            f"{BEST_MODEL_PATH} not found. Run initial_train() first."
        )
    with open(BEST_MODEL_PATH, "rb") as f:
        model = pickle.load(f)
    print(f"  [loaded] Loaded {BEST_MODEL_PATH.name}")
    return model

# Region csv utilities
# rolling window logic
# return true when threshold is hit, then triggers retraining feature

def _append_rolling(csv_path, new_rows: pd.DataFrame):
    """
    Append new_rows to the region CSV.
    When the file grows beyond ROLLING_KEEP_SIZE + ROLLING_SIZE,
    drop the oldest ROLLING_SIZE rows. Returns
    (updated_df, retrain_triggered).
    """
    new_rows = _ensure_training_metadata_columns(new_rows)
    if os.path.exists(csv_path):
        existing = _ensure_training_metadata_columns(pd.read_csv(csv_path))
        combined = pd.concat([existing, new_rows], ignore_index=True)
    else:
        combined = new_rows.copy()

    retrain_triggered = False
    threshold = ROLLING_KEEP_SIZE + ROLLING_SIZE
    while len(combined) >= threshold:
        combined          = combined.iloc[ROLLING_SIZE:].reset_index(drop=True)
        retrain_triggered = True
        print(f"  [rolling] Dropped oldest {ROLLING_SIZE} rows from "
              f"{os.path.basename(csv_path)}. "
              f"Remaining: {len(combined)} rows "
              f"(target: {ROLLING_KEEP_SIZE}).")

    combined.to_csv(csv_path, index=False)
    return combined, retrain_triggered


def _ensure_training_metadata_columns(df: pd.DataFrame):
    """Keep live/raw rows explicit about synthetic status and flood type labels."""
    df = df.copy()
    if SYNTHETIC_COL not in df.columns:
        df[SYNTHETIC_COL] = False
    else:
        df[SYNTHETIC_COL] = df[SYNTHETIC_COL].fillna(False)

    if FLOOD_TYPE_COL not in df.columns:
        df[FLOOD_TYPE_COL] = UNLABELLED_FLOOD_TYPE
    else:
        df[FLOOD_TYPE_COL] = df[FLOOD_TYPE_COL].replace("", np.nan)
        df[FLOOD_TYPE_COL] = df[FLOOD_TYPE_COL].fillna(UNLABELLED_FLOOD_TYPE)

    for column, default in TRAINING_METADATA_DEFAULTS.items():
        if column not in df.columns:
            df[column] = default
        else:
            df[column] = df[column].fillna(default)
    return df


def _model_training_view(df: pd.DataFrame):
    """Return only raw-format columns used by the current classifier."""
    return df[MODEL_COLUMNS].copy()

def ingest_sensor_data(new_data: pd.DataFrame, region: str = "a"):
    """
    CALLED BY: app.py /ingest endpoint
    Receives sensor data from the dashboard and saves it to the
    correct region CSV file. Returns True if the rolling threshold
    was hit and retraining should be triggered.

    Parameters:
      new_data : DataFrame with columns:
                 Date, Location, Rainfall_mm, WaterLevel_m,
                 SoilMoisture_pct, Elevation_m, FloodOccurrence
      region   : 'a' or 'b'
    """
    csv_path = REGION_A_CSV if region.lower() == "a" else REGION_B_CSV
    required = ["Date", "Location"] + FEATURES + [TARGET]
    missing  = [c for c in required if c not in new_data.columns]
    if missing:
        raise ValueError(f"New data is missing columns: {missing}")

    new_data         = new_data.copy()
    new_data["Date"] = pd.to_datetime(new_data["Date"])
    df, triggered    = _append_rolling(csv_path, new_data)

    print(f"  [region {region.upper()}] {len(new_data)} rows ingested. "
          f"Total: {len(df)} rows. Retrain triggered: {triggered}")
    return triggered

def _load_combined_regions():
    """
    Load and combine both region CSV files into one DataFrame.
    Used during retraining to train on all available data.
    """
    frames = []
    for csv_path in [REGION_A_CSV, REGION_B_CSV]:
        if os.path.exists(csv_path):
            frames.append(pd.read_csv(csv_path))
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True).drop_duplicates()


def _region_csv_path(region: str):
    region = region.lower()
    if region == "a":
        return REGION_A_CSV
    if region == "b":
        return REGION_B_CSV
    raise ValueError("region must be 'a' or 'b'")


def _load_region_data(region: str):
    csv_path = _region_csv_path(region)
    if not os.path.exists(csv_path):
        return pd.DataFrame()
    return pd.read_csv(csv_path)

# anchor set: top 50 most extreme flood events are saved permanently
# every retrain action re-injects them so the model neve forgets on identifying flood events
# SEVERITY = combined score of high rainfall + water level + soil moisture

def build_anchor_set(df, top_n=50):
    """
    Extract the top N most extreme flood events from a DataFrame
    and save them to anchor_set.csv permanently.
    """
    df = _ensure_training_metadata_columns(df)
    flood_rows = df[df[TARGET] == 1].copy()
    if flood_rows.empty:
        print("  [anchor] No flood rows found. Anchor set is empty.")
        return pd.DataFrame(columns=df.columns)

    flood_rows["severity"] = (
        flood_rows["Rainfall_mm"]      / df["Rainfall_mm"].max() +
        flood_rows["WaterLevel_m"]     / df["WaterLevel_m"].max() +
        flood_rows["SoilMoisture_pct"] / df["SoilMoisture_pct"].max()
    )
    anchor = flood_rows.nlargest(top_n, "severity").drop(columns="severity")
    anchor.to_csv(ANCHOR_FILE, index=False)
    print(f"  [anchor] {len(anchor)} extreme flood events preserved "
          f"→ {ANCHOR_FILE}")
    return anchor

# Evaluation and charts

def evaluate(model, X, y, label=""):
    """Score a model and return accuracy, F1, AUC, predictions."""
    y_pred      = model.predict(X)
    y_prob      = model.predict_proba(X)[:, 1]
    acc         = accuracy_score(y, y_pred)
    f1          = f1_score(y, y_pred, zero_division=0)
    fpr, tpr, _ = roc_curve(y, y_prob)
    roc_auc     = auc(fpr, tpr)
    if label:
        print(f"  [{label}] Accuracy={acc:.4f}  F1={f1:.4f}  AUC={roc_auc:.4f}")
    return {
        "acc": acc, "f1": f1, "auc": roc_auc,
        "y_pred": y_pred, "y_prob": y_prob
    }

def plot_results(model, X_test, y_test, metrics, version_tag):
    """Generate and save confusion matrix, feature importance, ROC curve."""
    y_pred = metrics["y_pred"]
    y_prob = metrics["y_prob"]

    fig = plt.figure(figsize=(18, 6), facecolor=BG_MAIN)
    fig.suptitle(
        f"Flood Prediction Model — NCR Philippines (v{version_tag})",
        fontsize=15, fontweight="bold", color="white", y=1.02
    )
    gs = gridspec.GridSpec(1, 3, figure=fig, wspace=0.4)

    # Confusion matrix
    ax1  = fig.add_subplot(gs[0])
    cm   = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(
        confusion_matrix=cm, display_labels=["No Flood", "Flood"]
    )
    disp.plot(ax=ax1, colorbar=False, cmap="Blues")
    for text in ax1.texts:
        val = int(text.get_text())
        text.set_fontsize(13)
        text.set_fontweight("bold")
        text.set_color("white" if val > 100 else "#1a1d27")
    style_ax(ax1, "Confusion Matrix")
    ax1.set_xlabel("Predicted Label", color=TEXT_COL)
    ax1.set_ylabel("True Label",      color=TEXT_COL)
    ax1.tick_params(colors=TEXT_COL)

    # Feature importance
    ax2         = fig.add_subplot(gs[1])
    importances = model.feature_importances_
    indices     = np.argsort(importances)[::-1]
    sorted_feat = [FEATURES[i] for i in indices]
    sorted_imp  = importances[indices]
    colors      = [ACCENT if i == 0 else "#78909c"
                   for i in range(len(sorted_feat))]
    bars        = ax2.barh(
        sorted_feat[::-1], sorted_imp[::-1],
        color=colors[::-1], edgecolor="none", height=0.55
    )
    for bar, val in zip(bars, sorted_imp[::-1]):
        ax2.text(
            bar.get_width() + 0.004,
            bar.get_y() + bar.get_height() / 2,
            f"{val:.3f}", va="center", ha="left",
            color=TEXT_COL, fontsize=9
        )
    ax2.set_xlabel("Importance Score", color=TEXT_COL)
    ax2.set_xlim(0, sorted_imp.max() + 0.06)
    ax2.grid(axis="x", color=GRID_COL, linestyle="--", linewidth=0.6)
    style_ax(ax2, "Feature Importance")

    # ROC curve
    ax3         = fig.add_subplot(gs[2])
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc     = auc(fpr, tpr)
    ax3.plot(fpr, tpr, color=ACCENT, lw=2.5, label=f"AUC = {roc_auc:.4f}")
    ax3.plot([0, 1], [0, 1], color="#546e7a", lw=1.2,
             linestyle="--", label="Random Classifier")
    ax3.fill_between(fpr, tpr, alpha=0.08, color=ACCENT)
    ax3.set_xlabel("False Positive Rate", color=TEXT_COL)
    ax3.set_ylabel("True Positive Rate",  color=TEXT_COL)
    ax3.legend(loc="lower right", fontsize=9,
               facecolor=BG_PANEL, edgecolor=GRID_COL, labelcolor=TEXT_COL)
    ax3.grid(color=GRID_COL, linestyle="--", linewidth=0.6)
    style_ax(ax3, "ROC Curve")

    plt.tight_layout()
    out = f"flood_model_results_v{version_tag}.png"
    plt.savefig(out, dpi=180, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    plt.close(fig)
    print(f"  [chart] Saved → {out}")

# Initial training
# locks away raw data as holdout_test.csv
# builds the anchor set from training data
# seeds both csv files by splitting training data evenly
# trains first model
# saves it to archive and sets as best_model.pkl

def initial_train(train_csv, test_csv):
    print("\n" + "="*55)
    print("  STEP 1 — INITIAL TRAINING")
    print("="*55)

    train_df = _ensure_training_metadata_columns(pd.read_csv(train_csv))
    test_df  = _ensure_training_metadata_columns(pd.read_csv(test_csv))

    # Lock away holdout — never train on this
    test_df.to_csv(HOLDOUT_FILE, index=False)
    print(f"  [holdout] Fixed test set saved → {HOLDOUT_FILE}")

    # Build anchor set from training data
    build_anchor_set(train_df)

    # Seed both region CSVs by splitting training data in half
    # UPDATE THIS SPLIT when region names and boundaries are confirmed
    mid = len(train_df) // 2
    train_df.iloc[:mid].to_csv(REGION_A_CSV, index=False)
    train_df.iloc[mid:].to_csv(REGION_B_CSV, index=False)
    print(f"  [regions] Seeded {REGION_A_CSV} ({mid} rows) "
          f"and {REGION_B_CSV} ({len(train_df)-mid} rows)")

    X_train, y_train = train_df[FEATURES], train_df[TARGET]
    X_test,  y_test  = test_df[FEATURES],  test_df[TARGET]

    model = RandomForestClassifier(**RF_PARAMS)
    model.fit(X_train, y_train)

    metrics = evaluate(model, X_test, y_test, label="initial")
    report  = classification_report(
        y_test, metrics["y_pred"], target_names=["No Flood", "Flood"]
    )
    print(f"\n  Overall Accuracy : {metrics['acc']:.4f} "
          f"({metrics['acc']*100:.2f}%)")
    print(f"  F1 Score         : {metrics['f1']:.4f}")
    print(f"  AUC              : {metrics['auc']:.4f}")
    print("  " + "-"*50)
    print(report)

    version_tag = datetime.now().strftime("%Y%m%d_%H%M%S")
    save_to_archive_global(model, version_tag, X_test, y_test)
    plot_results(model, X_test, y_test, metrics, version_tag)

    return model

# Retrain
# triggered automatically by app.py when /ingest detects
# triggered when rolling threshold is hit
# combines both csv files then re-injects to anchor set
# trains a new model
# saves to archive, remove worst performing model if exceeds 5
# returns True for app.py to tell dashboard to load best_model.pkl

def retrain():
    print("\n" + "="*55)
    print("  STEP 2 — RETRAINING")
    print("="*55)

    if not os.path.exists(HOLDOUT_FILE):
        print("  [skip] No holdout found. Run initial_train() first.")
        return False

    holdout = pd.read_csv(HOLDOUT_FILE)
    X_hold  = holdout[FEATURES]
    y_hold  = holdout[TARGET]

    # Load and combine both region CSVs
    combined = _load_combined_regions()
    if combined.empty:
        print("  [skip] No region data found.")
        return False

    # Re-inject anchor set so model never forgets extreme events
    if os.path.exists(ANCHOR_FILE):
        anchor   = _ensure_training_metadata_columns(pd.read_csv(ANCHOR_FILE))
        combined = pd.concat([combined, anchor], ignore_index=True)
        combined = combined.drop_duplicates()
        print(f"  [anchor] Re-injected {len(anchor)} anchor rows.")

    train_view = _model_training_view(combined)
    flood_count = train_view[TARGET].sum()
    print(f"  [data] Training on {len(train_view)} rows, "
          f"{int(flood_count)} flood events.")

    if flood_count < 5:
        print(f"  [warning] Too few flood examples ({int(flood_count)}). "
              f"Skipping retrain.")
        return False

    candidate = RandomForestClassifier(**RF_PARAMS)
    candidate.fit(train_view[FEATURES], train_view[TARGET])

    metrics     = evaluate(candidate, X_hold, y_hold, label="new model")
    version_tag = datetime.now().strftime("%Y%m%d_%H%M%S")

    save_to_archive_global(candidate, version_tag, X_hold, y_hold)
    plot_results(candidate, X_hold, y_hold, metrics, version_tag)

    report = classification_report(
        y_hold, metrics["y_pred"], target_names=["No Flood", "Flood"]
    )
    print(f"\n  Overall Accuracy : {metrics['acc']:.4f} "
          f"({metrics['acc']*100:.2f}%)")
    print(f"  F1 Score         : {metrics['f1']:.4f}")
    print(f"  AUC              : {metrics['auc']:.4f}")
    print("  " + "-"*50)
    print(report)

    return True   # signals to app.py that best_model.pkl was updated


def retrain_region(region: str):
    """Retrain and deploy the best model for one region only."""
    region = region.lower()
    print("\n" + "="*55)
    print(f"  STEP 2 - REGION {region.upper()} RETRAINING")
    print("="*55)

    if not os.path.exists(HOLDOUT_FILE):
        print("  [skip] No holdout found. Run initial_train() first.")
        return False

    holdout = pd.read_csv(HOLDOUT_FILE)
    X_hold  = holdout[FEATURES]
    y_hold  = holdout[TARGET]

    training_df = _load_region_data(region)
    if training_df.empty:
        print(f"  [skip] No region {region.upper()} rolling data found.")
        return False

    if os.path.exists(ANCHOR_FILE):
        anchor = _ensure_training_metadata_columns(pd.read_csv(ANCHOR_FILE))
        training_df = pd.concat([training_df, anchor], ignore_index=True)
        training_df = training_df.drop_duplicates()
        print(f"  [anchor:{region}] Re-injected {len(anchor)} shared anchor rows.")

    train_view = _model_training_view(training_df)
    flood_count = train_view[TARGET].sum()
    print(f"  [data:{region}] Training on {len(train_view)} rows, "
          f"{int(flood_count)} flood events.")

    if flood_count < 5:
        print(f"  [warning:{region}] Too few flood examples ({int(flood_count)}). "
              f"Skipping retrain.")
        return False

    candidate = RandomForestClassifier(**RF_PARAMS)
    candidate.fit(train_view[FEATURES], train_view[TARGET])

    metrics = evaluate(candidate, X_hold, y_hold, label=f"region {region}")
    version_tag = datetime.now().strftime("%Y%m%d_%H%M%S")

    save_region_model(candidate, region, version_tag, X_hold, y_hold)
    plot_results(candidate, X_hold, y_hold, metrics, f"{region}_{version_tag}")

    report = classification_report(
        y_hold, metrics["y_pred"], target_names=["No Flood", "Flood"]
    )
    print(f"\n  Region {region.upper()} Accuracy : {metrics['acc']:.4f} "
          f"({metrics['acc']*100:.2f}%)")
    print(f"  F1 Score           : {metrics['f1']:.4f}")
    print(f"  AUC                : {metrics['auc']:.4f}")
    print("  " + "-"*50)
    print(report)

    return True

# Live prediction
# called by apppy /predict function every time dashboard sends a live sensor reading loads best_model.pkl
# dashboard returns flood occurence classification and confidence score
# both values are sent to rule-based classifier

def predict_live(rainfall_mm, water_level_m, soil_moisture_pct, elevation_m):
    model = load_best_model()

    X = pd.DataFrame([{
        "Rainfall_mm":       rainfall_mm,
        "WaterLevel_m":      water_level_m,
        "SoilMoisture_pct":  soil_moisture_pct,
        "Elevation_m":       elevation_m,
    }])

    confidence_score = round(float(model.predict_proba(X)[0][1]), 4)
    flood_occurrence = 1 if confidence_score >= 0.5 else 0

    return {
        "flood_occurrence": flood_occurrence,
        "confidence_score": confidence_score,
    }

if __name__ == "__main__":

    # Run once: initial training
    initial_train(
        train_csv=RAW_DIR / "flood_train_with_synthetic.csv",
        test_csv=RAW_DIR / "flood_test_real.csv"
    )

    # Simulate Region A sensor batch
    # Replace with actual sensor feed when dashboard is connected
    region_a_batch = pd.DataFrame({
        "Date":             [f"2021-01-{str(i).zfill(2)}" for i in range(1,11)],
        "Location":         ["Marikina"] * 10,
        "Rainfall_mm":      [38.5,5.2,42.1,10.0,3.1,31.0,28.5,6.7,45.0,2.3],
        "WaterLevel_m":     [4.1,0.8,4.8,1.2,0.6,3.5,3.2,0.9,5.1,0.5],
        "SoilMoisture_pct": [30.0,12.0,35.0,14.0,10.0,28.0,26.0,11.0,38.0,9.0],
        "Elevation_m":      [15,5,5,43,15,5,5,43,15,5],
        "FloodOccurrence":  [1,0,1,0,0,1,1,0,1,0],
    })

    # Simulate Region B sensor batch
    region_b_batch = pd.DataFrame({
        "Date":             [f"2021-01-{str(i).zfill(2)}" for i in range(1,11)],
        "Location":         ["Pasig"] * 10,
        "Rainfall_mm":      [22.1,4.5,36.0,8.0,2.5,27.0,19.5,5.1,40.0,1.8],
        "WaterLevel_m":     [3.2,0.7,4.1,1.0,0.5,3.1,2.8,0.8,4.6,0.4],
        "SoilMoisture_pct": [25.0,11.0,31.0,13.0,9.0,24.0,22.0,10.0,34.0,8.0],
        "Elevation_m":      [10,5,5,15,10,5,5,15,10,5],
        "FloodOccurrence":  [1,0,1,0,0,1,0,0,1,0],
    })

    trigger_a = ingest_sensor_data(region_a_batch, region="a")
    trigger_b = ingest_sensor_data(region_b_batch, region="b")

    # Retrain only if rolling threshold was hit
    if trigger_a or trigger_b:
        retrain()
    else:
        print(f"\n  [info] Rolling threshold not reached yet. "
              f"Need {ROLLING_SIZE} rows per region to trigger retrain.")

    # Live prediction example
    print("\n" + "="*55)
    print("  LIVE PREDICTION")
    print("="*55)
    result = predict_live(
        rainfall_mm       = 40.0,
        water_level_m     = 4.2,
        soil_moisture_pct = 32.0,
        elevation_m       = 5
    )
    print(f"\n  flood_occurrence : {result['flood_occurrence']} "
          f"({'FLOOD' if result['flood_occurrence'] else 'NO FLOOD'})")
    print(f"  confidence_score : {result['confidence_score']} "
          f"({result['confidence_score']*100:.1f}%)")
    print(f" Passing to Simulink controller")
