# -*- coding: utf-8 -*-
"""FloodPredictiveModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lyTUJS9S7jaZ1LKCV2LHQjnxwphXWDqE

## Flood Prediction Model - Random Forest Classification with Continual Learning Pipeline

###Features:
  - Initial training on historical + synthetic data
  - Receives new sensor data from two csv files generated from the dashbaord
  - Rolling window: every 1000 new rows, delete the first 1000 old rows
  - Retrain automatically when rolling threshold is hit
  - Model archive: 5 models maximum, worst model is deleted when cap is exceeded
  - best_model.pkl: always points to the best performing model
  - Live prediction: returns flood occurence classification with confidence score
  - Notifies dashboard when bes model has been updated in the folder

###How to connect to dashboard:
  - Dashbaord calls two API endpoints (defined in app.py)
  - POST /ingest = sending sensor data here to save and trigger retrain
  - POST /predict = sending live sensor values, gets flood prediction back
"""

import os
import pickle
import shutil
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from datetime import datetime
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    confusion_matrix, ConfusionMatrixDisplay,
    classification_report, accuracy_score,
    roc_curve, auc, f1_score
)

FEATURES      = ["Rainfall_mm", "WaterLevel_m", "SoilMoisture_pct", "Elevation_m"]
TARGET        = "FloodOccurrence"

# Region CSV files
REGION_A_CSV  = "region_a_data.csv"
REGION_B_CSV  = "region_b_data.csv"

# Retraining settings
ROLLING_SIZE  = 1000    # new rows before retrain triggers + oldest rows dropped
MAX_MODELS    = 5       # max models kept in archive at any time

# File paths
MODEL_DIR     = "models"           # folder for all saved model versions
BEST_MODEL    = "best_model.pkl"   # always the best model — dashboard loads this
HOLDOUT_FILE  = "holdout_test.csv" # fixed test set, never trained on
ANCHOR_FILE   = "anchor_set.csv"   # top 50 extreme flood events, never deleted

# Random Forest settings
RF_PARAMS = dict(
    n_estimators = 200,
    max_depth    = 10,
    random_state = 42,
    n_jobs       = -1,
)

os.makedirs(MODEL_DIR, exist_ok=True)

# Chart Styling
ACCENT   = "#4fc3f7"
BG_MAIN  = "#0f1117"
BG_PANEL = "#1a1d27"
TEXT_COL = "#e0e0e0"
GRID_COL = "#2e3148"

def style_ax(ax, title):
    ax.set_facecolor(BG_PANEL)
    ax.tick_params(colors=TEXT_COL, labelsize=9)
    ax.xaxis.label.set_color(TEXT_COL)
    ax.yaxis.label.set_color(TEXT_COL)
    ax.title.set_color(TEXT_COL)
    ax.set_title(title, fontsize=12, fontweight="bold", pad=10)
    for spine in ax.spines.values():
        spine.set_edgecolor(GRID_COL)

# Model archive utilities
# - keeps up to maximum 5 models
# - if there are more than 5 models, all are scored and the worst performing model gets deleted
# - best performing model gets copied to best_model.pkl so the dahabord always knows which model to use

def _score_model_file(pkl_path, X_hold, y_hold):
    """
    Load a saved model file and return its F1 score on the holdout set.
    Used to compare models against each other.
    """
    with open(pkl_path, "rb") as f:
        m = pickle.load(f)
    y_pred = m.predict(X_hold)
    return f1_score(y_hold, y_pred, zero_division=0)

def get_archive():
    """
    Return a sorted list of all saved model file paths in models/ folder.
    Excludes best_model.pkl itself.
    """
    files = sorted([
        f for f in os.listdir(MODEL_DIR)
        if f.endswith(".pkl") and f != os.path.basename(BEST_MODEL)
    ])
    return [os.path.join(MODEL_DIR, f) for f in files]

def _update_best_model(X_hold, y_hold):
    """
    Score all archived models, find the best one, and copy it to
    best_model.pkl. The dashboard always loads best_model.pkl —
    this ensures it always gets the best performing version.
    """
    archive = get_archive()
    if not archive:
        return None

    scores    = {p: _score_model_file(p, X_hold, y_hold) for p in archive}
    best_path = max(scores, key=scores.get)
    best_f1   = scores[best_path]

    shutil.copy(best_path, BEST_MODEL)
    print(f"  [best] best_model.pkl updated → "
          f"{os.path.basename(best_path)} (F1={best_f1:.4f})")
    return best_path

def save_to_archive(model, version_tag, X_hold, y_hold):
    """
    Save a new model to the archive with a timestamp filename.
    If archive now exceeds MAX_MODELS, score all models and delete
    the worst performer. Then update best_model.pkl.
    """
    path = os.path.join(MODEL_DIR, f"model_{version_tag}.pkl")
    with open(path, "wb") as f:
        pickle.dump(model, f)
    print(f"  [archive] Saved → {path}")

    archive = get_archive()
    if len(archive) > MAX_MODELS:
        print(f"  [archive] Cap of {MAX_MODELS} exceeded. "
              f"Scoring all models...")
        scores = {p: _score_model_file(p, X_hold, y_hold) for p in archive}
        for p, s in scores.items():
            print(f"    {os.path.basename(p)}: F1={s:.4f}")
        worst = min(scores, key=scores.get)
        os.remove(worst)
        print(f"  [archive] Removed worst → {os.path.basename(worst)} "
              f"(F1={scores[worst]:.4f})")

    _update_best_model(X_hold, y_hold)

def load_best_model():
    """
    Load best_model.pkl — the best performing model in the archive.
    This is what predict_live() uses for every prediction.
    The dashboard is told to reload this file when best_model_updated=True
    is returned from the /ingest API endpoint.
    """
    if not os.path.exists(BEST_MODEL):
        raise RuntimeError(
            "best_model.pkl not found. Run initial_train() first."
        )
    with open(BEST_MODEL, "rb") as f:
        model = pickle.load(f)
    print(f"  [loaded] Loaded best_model.pkl")
    return model

# Region csv utilities
# rolling window logic
# return true when threshold is hit, then triggers retraining feature

def _append_rolling(csv_path, new_rows: pd.DataFrame):
    """
    Append new_rows to the region CSV.
    When the file grows beyond 2x ROLLING_SIZE, drop the oldest
    ROLLING_SIZE rows. Returns (updated_df, retrain_triggered).
    """
    if os.path.exists(csv_path):
        existing = pd.read_csv(csv_path)
        combined = pd.concat([existing, new_rows], ignore_index=True)
    else:
        combined = new_rows.copy()

    retrain_triggered = False
    while len(combined) >= ROLLING_SIZE * 2:
        combined          = combined.iloc[ROLLING_SIZE:].reset_index(drop=True)
        retrain_triggered = True
        print(f"  [rolling] Dropped oldest {ROLLING_SIZE} rows from "
              f"{os.path.basename(csv_path)}. "
              f"Remaining: {len(combined)} rows.")

    combined.to_csv(csv_path, index=False)
    return combined, retrain_triggered

def ingest_sensor_data(new_data: pd.DataFrame, region: str = "a"):
    """
    CALLED BY: app.py /ingest endpoint
    Receives sensor data from the dashboard and saves it to the
    correct region CSV file. Returns True if the rolling threshold
    was hit and retraining should be triggered.

    Parameters:
      new_data : DataFrame with columns:
                 Date, Location, Rainfall_mm, WaterLevel_m,
                 SoilMoisture_pct, Elevation_m, FloodOccurrence
      region   : 'a' or 'b'
    """
    csv_path = REGION_A_CSV if region.lower() == "a" else REGION_B_CSV
    required = ["Date", "Location"] + FEATURES + [TARGET]
    missing  = [c for c in required if c not in new_data.columns]
    if missing:
        raise ValueError(f"New data is missing columns: {missing}")

    new_data         = new_data.copy()
    new_data["Date"] = pd.to_datetime(new_data["Date"])
    df, triggered    = _append_rolling(csv_path, new_data)

    print(f"  [region {region.upper()}] {len(new_data)} rows ingested. "
          f"Total: {len(df)} rows. Retrain triggered: {triggered}")
    return triggered

def _load_combined_regions():
    """
    Load and combine both region CSV files into one DataFrame.
    Used during retraining to train on all available data.
    """
    frames = []
    for csv_path in [REGION_A_CSV, REGION_B_CSV]:
        if os.path.exists(csv_path):
            frames.append(pd.read_csv(csv_path))
    if not frames:
        return pd.DataFrame()
    return pd.concat(frames, ignore_index=True).drop_duplicates()

# anchor set: top 50 most extreme flood events are saved permanently
# every retrain action re-injects them so the model neve forgets on identifying flood events
# SEVERITY = combined score of high rainfall + water level + soil moisture

def build_anchor_set(df, top_n=50):
    """
    Extract the top N most extreme flood events from a DataFrame
    and save them to anchor_set.csv permanently.
    """
    flood_rows = df[df[TARGET] == 1].copy()
    if flood_rows.empty:
        print("  [anchor] No flood rows found. Anchor set is empty.")
        return pd.DataFrame(columns=df.columns)

    flood_rows["severity"] = (
        flood_rows["Rainfall_mm"]      / df["Rainfall_mm"].max() +
        flood_rows["WaterLevel_m"]     / df["WaterLevel_m"].max() +
        flood_rows["SoilMoisture_pct"] / df["SoilMoisture_pct"].max()
    )
    anchor = flood_rows.nlargest(top_n, "severity").drop(columns="severity")
    anchor.to_csv(ANCHOR_FILE, index=False)
    print(f"  [anchor] {len(anchor)} extreme flood events preserved "
          f"→ {ANCHOR_FILE}")
    return anchor

# Evaluation and charts

def evaluate(model, X, y, label=""):
    """Score a model and return accuracy, F1, AUC, predictions."""
    y_pred      = model.predict(X)
    y_prob      = model.predict_proba(X)[:, 1]
    acc         = accuracy_score(y, y_pred)
    f1          = f1_score(y, y_pred, zero_division=0)
    fpr, tpr, _ = roc_curve(y, y_prob)
    roc_auc     = auc(fpr, tpr)
    if label:
        print(f"  [{label}] Accuracy={acc:.4f}  F1={f1:.4f}  AUC={roc_auc:.4f}")
    return {
        "acc": acc, "f1": f1, "auc": roc_auc,
        "y_pred": y_pred, "y_prob": y_prob
    }

def plot_results(model, X_test, y_test, metrics, version_tag):
    """Generate and save confusion matrix, feature importance, ROC curve."""
    y_pred = metrics["y_pred"]
    y_prob = metrics["y_prob"]

    fig = plt.figure(figsize=(18, 6), facecolor=BG_MAIN)
    fig.suptitle(
        f"Flood Prediction Model — NCR Philippines (v{version_tag})",
        fontsize=15, fontweight="bold", color="white", y=1.02
    )
    gs = gridspec.GridSpec(1, 3, figure=fig, wspace=0.4)

    # Confusion matrix
    ax1  = fig.add_subplot(gs[0])
    cm   = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(
        confusion_matrix=cm, display_labels=["No Flood", "Flood"]
    )
    disp.plot(ax=ax1, colorbar=False, cmap="Blues")
    for text in ax1.texts:
        val = int(text.get_text())
        text.set_fontsize(13)
        text.set_fontweight("bold")
        text.set_color("white" if val > 100 else "#1a1d27")
    style_ax(ax1, "Confusion Matrix")
    ax1.set_xlabel("Predicted Label", color=TEXT_COL)
    ax1.set_ylabel("True Label",      color=TEXT_COL)
    ax1.tick_params(colors=TEXT_COL)

    # Feature importance
    ax2         = fig.add_subplot(gs[1])
    importances = model.feature_importances_
    indices     = np.argsort(importances)[::-1]
    sorted_feat = [FEATURES[i] for i in indices]
    sorted_imp  = importances[indices]
    colors      = [ACCENT if i == 0 else "#78909c"
                   for i in range(len(sorted_feat))]
    bars        = ax2.barh(
        sorted_feat[::-1], sorted_imp[::-1],
        color=colors[::-1], edgecolor="none", height=0.55
    )
    for bar, val in zip(bars, sorted_imp[::-1]):
        ax2.text(
            bar.get_width() + 0.004,
            bar.get_y() + bar.get_height() / 2,
            f"{val:.3f}", va="center", ha="left",
            color=TEXT_COL, fontsize=9
        )
    ax2.set_xlabel("Importance Score", color=TEXT_COL)
    ax2.set_xlim(0, sorted_imp.max() + 0.06)
    ax2.grid(axis="x", color=GRID_COL, linestyle="--", linewidth=0.6)
    style_ax(ax2, "Feature Importance")

    # ROC curve
    ax3         = fig.add_subplot(gs[2])
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc     = auc(fpr, tpr)
    ax3.plot(fpr, tpr, color=ACCENT, lw=2.5, label=f"AUC = {roc_auc:.4f}")
    ax3.plot([0, 1], [0, 1], color="#546e7a", lw=1.2,
             linestyle="--", label="Random Classifier")
    ax3.fill_between(fpr, tpr, alpha=0.08, color=ACCENT)
    ax3.set_xlabel("False Positive Rate", color=TEXT_COL)
    ax3.set_ylabel("True Positive Rate",  color=TEXT_COL)
    ax3.legend(loc="lower right", fontsize=9,
               facecolor=BG_PANEL, edgecolor=GRID_COL, labelcolor=TEXT_COL)
    ax3.grid(color=GRID_COL, linestyle="--", linewidth=0.6)
    style_ax(ax3, "ROC Curve")

    plt.tight_layout()
    out = f"flood_model_results_v{version_tag}.png"
    plt.savefig(out, dpi=180, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    plt.show()
    print(f"  [chart] Saved → {out}")

# Initial training
# locks away raw data as holdout_test.csv
# builds the anchor set from training data
# seeds both csv files by splitting training data evenly
# trains first model
# saves it to archive and sets as best_model.pkl

def initial_train(train_csv, test_csv):
    print("\n" + "="*55)
    print("  STEP 1 — INITIAL TRAINING")
    print("="*55)

    train_df = pd.read_csv(train_csv)
    test_df  = pd.read_csv(test_csv)

    # Lock away holdout — never train on this
    test_df.to_csv(HOLDOUT_FILE, index=False)
    print(f"  [holdout] Fixed test set saved → {HOLDOUT_FILE}")

    # Build anchor set from training data
    build_anchor_set(train_df)

    # Seed both region CSVs by splitting training data in half
    # UPDATE THIS SPLIT when region names and boundaries are confirmed
    mid = len(train_df) // 2
    train_df.iloc[:mid].to_csv(REGION_A_CSV, index=False)
    train_df.iloc[mid:].to_csv(REGION_B_CSV, index=False)
    print(f"  [regions] Seeded {REGION_A_CSV} ({mid} rows) "
          f"and {REGION_B_CSV} ({len(train_df)-mid} rows)")

    X_train, y_train = train_df[FEATURES], train_df[TARGET]
    X_test,  y_test  = test_df[FEATURES],  test_df[TARGET]

    model = RandomForestClassifier(**RF_PARAMS)
    model.fit(X_train, y_train)

    metrics = evaluate(model, X_test, y_test, label="initial")
    report  = classification_report(
        y_test, metrics["y_pred"], target_names=["No Flood", "Flood"]
    )
    print(f"\n  Overall Accuracy : {metrics['acc']:.4f} "
          f"({metrics['acc']*100:.2f}%)")
    print(f"  F1 Score         : {metrics['f1']:.4f}")
    print(f"  AUC              : {metrics['auc']:.4f}")
    print("  " + "-"*50)
    print(report)

    version_tag = datetime.now().strftime("%Y%m%d_%H%M%S")
    save_to_archive(model, version_tag, X_test, y_test)
    plot_results(model, X_test, y_test, metrics, version_tag)

    return model

# Retrain
# triggered automatically by app.py when /ingest detects
# triggered when rolling threshold is hit
# combines both csv files then re-injects to anchor set
# trains a new model
# saves to archive, remove worst performing model if exceeds 5
# returns True for app.py to tell dashboard to load best_model.pkl

def retrain():
    print("\n" + "="*55)
    print("  STEP 2 — RETRAINING")
    print("="*55)

    if not os.path.exists(HOLDOUT_FILE):
        print("  [skip] No holdout found. Run initial_train() first.")
        return False

    holdout = pd.read_csv(HOLDOUT_FILE)
    X_hold  = holdout[FEATURES]
    y_hold  = holdout[TARGET]

    # Load and combine both region CSVs
    combined = _load_combined_regions()
    if combined.empty:
        print("  [skip] No region data found.")
        return False

    # Re-inject anchor set so model never forgets extreme events
    if os.path.exists(ANCHOR_FILE):
        anchor   = pd.read_csv(ANCHOR_FILE)
        combined = pd.concat([combined, anchor], ignore_index=True)
        combined = combined.drop_duplicates()
        print(f"  [anchor] Re-injected {len(anchor)} anchor rows.")

    flood_count = combined[TARGET].sum()
    print(f"  [data] Training on {len(combined)} rows, "
          f"{int(flood_count)} flood events.")

    if flood_count < 5:
        print(f"  [warning] Too few flood examples ({int(flood_count)}). "
              f"Skipping retrain.")
        return False

    candidate = RandomForestClassifier(**RF_PARAMS)
    candidate.fit(combined[FEATURES], combined[TARGET])

    metrics     = evaluate(candidate, X_hold, y_hold, label="new model")
    version_tag = datetime.now().strftime("%Y%m%d_%H%M%S")

    save_to_archive(candidate, version_tag, X_hold, y_hold)
    plot_results(candidate, X_hold, y_hold, metrics, version_tag)

    report = classification_report(
        y_hold, metrics["y_pred"], target_names=["No Flood", "Flood"]
    )
    print(f"\n  Overall Accuracy : {metrics['acc']:.4f} "
          f"({metrics['acc']*100:.2f}%)")
    print(f"  F1 Score         : {metrics['f1']:.4f}")
    print(f"  AUC              : {metrics['auc']:.4f}")
    print("  " + "-"*50)
    print(report)

    return True   # signals to app.py that best_model.pkl was updated

# Live prediction
# called by apppy /predict function every time dashboard sends a live sensor reading loads best_model.pkl
# dashboard returns flood occurence classification and confidence score
# both values are sent to rule-based classifier

def predict_live(rainfall_mm, water_level_m, soil_moisture_pct, elevation_m):
    model = load_best_model()

    X = pd.DataFrame([{
        "Rainfall_mm":       rainfall_mm,
        "WaterLevel_m":      water_level_m,
        "SoilMoisture_pct":  soil_moisture_pct,
        "Elevation_m":       elevation_m,
    }])

    confidence_score = round(float(model.predict_proba(X)[0][1]), 4)
    flood_occurrence = 1 if confidence_score >= 0.5 else 0

    return {
        "flood_occurrence": flood_occurrence,
        "confidence_score": confidence_score,
    }

if __name__ == "__main__":

    # Run once: initial training
    initial_train(
        train_csv="flood_train_with_synthetic.csv",
        test_csv="flood_test_real.csv"
    )

    # Simulate Region A sensor batch
    # Replace with actual sensor feed when dashboard is connected
    region_a_batch = pd.DataFrame({
        "Date":             [f"2021-01-{str(i).zfill(2)}" for i in range(1,11)],
        "Location":         ["Marikina"] * 10,
        "Rainfall_mm":      [38.5,5.2,42.1,10.0,3.1,31.0,28.5,6.7,45.0,2.3],
        "WaterLevel_m":     [4.1,0.8,4.8,1.2,0.6,3.5,3.2,0.9,5.1,0.5],
        "SoilMoisture_pct": [30.0,12.0,35.0,14.0,10.0,28.0,26.0,11.0,38.0,9.0],
        "Elevation_m":      [15,5,5,43,15,5,5,43,15,5],
        "FloodOccurrence":  [1,0,1,0,0,1,1,0,1,0],
    })

    # Simulate Region B sensor batch
    region_b_batch = pd.DataFrame({
        "Date":             [f"2021-01-{str(i).zfill(2)}" for i in range(1,11)],
        "Location":         ["Pasig"] * 10,
        "Rainfall_mm":      [22.1,4.5,36.0,8.0,2.5,27.0,19.5,5.1,40.0,1.8],
        "WaterLevel_m":     [3.2,0.7,4.1,1.0,0.5,3.1,2.8,0.8,4.6,0.4],
        "SoilMoisture_pct": [25.0,11.0,31.0,13.0,9.0,24.0,22.0,10.0,34.0,8.0],
        "Elevation_m":      [10,5,5,15,10,5,5,15,10,5],
        "FloodOccurrence":  [1,0,1,0,0,1,0,0,1,0],
    })

    trigger_a = ingest_sensor_data(region_a_batch, region="a")
    trigger_b = ingest_sensor_data(region_b_batch, region="b")

    # Retrain only if rolling threshold was hit
    if trigger_a or trigger_b:
        retrain()
    else:
        print(f"\n  [info] Rolling threshold not reached yet. "
              f"Need {ROLLING_SIZE} rows per region to trigger retrain.")

    # Live prediction example
    print("\n" + "="*55)
    print("  LIVE PREDICTION")
    print("="*55)
    result = predict_live(
        rainfall_mm       = 40.0,
        water_level_m     = 4.2,
        soil_moisture_pct = 32.0,
        elevation_m       = 5
    )
    print(f"\n  flood_occurrence : {result['flood_occurrence']} "
          f"({'FLOOD' if result['flood_occurrence'] else 'NO FLOOD'})")
    print(f"  confidence_score : {result['confidence_score']} "
          f"({result['confidence_score']*100:.1f}%)")
    print(f" Passing to Simulink controller")
